### ISSUE TITLE
Whats in a tweet?

### ISSUE THREAD

**Issue by OriAboodi** [NWChen/banshee#9]
Hey guys,

Right now, I included only a few things about tweets: username, link, a few stats on them, date, and content. 
What other attributes of a tweet do we think we should include?
Let's find the most important ones, and see if I can manage to scrape them. Location may be impossible/much harder while doing web scraping, I haven't tried yet but if we decide we need it, I'll take a look.

In general, let's try to prioritize what the next developments should be:
- add additional attributes to tweets
- add additional functionalities like get all tweets of a certain user, get the retweets, filter by location

Each one of the added functionalities will take a bit of work since scraping is much harder than the twitter API, so let's pinpoint a few to get done before the class is over.

**Comment by pr** [comment]
@OriAboodi I think to answer this question we need to think about our ultimate goal. What you have now is enough for the alert feature, I don't know what other features we want to implement? The jury is still out on the map/location data because I don't think as a group we've completely defined what "taking the pulse of a region" is going to entail. 

Did you implement the real time "data firehouse"?

**Comment by OriAboodi** [comment]
@pr I agree, we need to think about it with the big picture in mind. So perhaps we will want to focus now only on location-type things and set that as the goal for next week, whereas other functionalities can be added if we have more time

**Comment by pr** [comment]
@NWChen I agree. Let's just keep in mind Ori's point about make sure at the end of this we have at least one working feature we can show off the last day.

**Comment by OriAboodi** [comment]
@pr and @NWChen 
I opened a different thread about the types of requests I implemented, so I'm closing this one for now. We'll come back to what type of information we want to see in a tweet.
